 export const DHeader: IHeader = {
  characterName: "",
  classAndLevel: "",
  expirience: "",
  origin: "",
  playerName: "",
  species: "",
  worldView: "",
}
export const DInventory: IInventory = {
  copperCoins: 0,
  electrumCoins: 0,
  goldenCoins: 0,
  otherItems: "",
  platinumCoins: 0,
  silverCoins: 0,
}
export const DDescription: IDescription = {
  bonds: "",
  flaws: "",
  ideals: "",
  personality: "",
}
export const DCombat: ICombat = {
  armorClass: "",
  currentHP: "",
  diceName: "",
  failureFirst: false,
  failureSecond: false,
  failureThird: false,
  initiative: "",
  maxHP: "",
  speed: "",
  successFirst: false,
  successSecond: false,
  successThird: false,
  temporaryHP: "",
  totalHD: "",
}
export const DAttackSpells: IAttacksSpells = {
  firstWeaponBonus: "",
  firstWeaponDamage: "",
  firstWeaponName: "",
  otherWeaponSpells: "",
  secondWeaponBonus: "",
  secondWeaponDamage: "",
  secondWeaponName: "",
  thirdWeaponBonus: "",
  thirdWeapondamage: "",
  thirdWeaponName: "",
}
export const DStats: IStats = {
  charisma: 0,
  constitution: 0,
  dexterity: 0,
  inspiration: 0,
  intelligence: 0,
  profienceBonus: "",
  strength: 0,
  wisdom: 0,

  charismaChalChb: false,
  constitutionChalChb: false,
  dexterityChalChb: false,
  intelligenceChalChb: false,
  strengthChalChb: false,
  wisdomChalChb: false,

  charismaChalVal: 0,
  constitutionChalVal: 0,
  dexterityChalVal: 0,
  intelligenceChalVal: 0,
  strengthChalVal: 0,
  wisdomChalVal: 0,

  acrobaticsChb: false,
  arcanaChb: false,
  athleticsChb: false,
  deceptionChb: false,
  handlingChb: false,
  historyChb: false,
  insightChb: false,
  intimidationChb: false,
  investigationChb: false,
  medicineChb: false,
  natureChb: false,
  perceptionChb: false,
  perfomanceChb: false,
  persuasionChb: false,
  religionChb: false,
  sleightOfHandChb: false,
  stealthChb: false,
  survivalChb: false,

  acrobaticsVal: 0,
  arcanaVal: 0,
  athleticsVal: 0,
  deceptionVal: 0,
  handlingVal: 0,
  historyVal: 0,
  insightVal: 0,
  intimidationVal: 0,
  investigationVal: 0,
  medicineVal: 0,
  natureVal: 0,
  perceptionVal: 0,
  perfomanceVal: 0,
  persuasionVal: 0,
  religionVal: 0,
  sleightOfHandVal: 0,
  stealthVal: 0,
  survivalVal: 0,
}
